### ISSUE TITLE
What is this repository for?

### ISSUE THREAD

**Issue by svalordev** [benawad/astral-bugs#22]
Just out of curiosity.

**Comment by shaurya-blip** [comment]
BTW are you making your new project OPEN SOURCE?

**Comment by amenabe22** [comment]
I don't think that will happen :(

**Comment by ghost** [comment]
> BTW are you making your new project OPEN SOURCE?

Nah, Ben said he wasn't going to make it open source.

**Comment by ghost** [comment]
For bug reports?
