### ISSUE TITLE
onlyfans banned sexually explicit content

### ISSUE THREAD

**Issue by Assassin-1234** [benawad/astral-bugs#23]
since onlyfans banned sexually explicit content and astrals is near finished, why not allow sexually explicit content on it? it would act like a replacement for onlyfans and you will get users real quick

**Comment by ghost** [comment]
hmm i dont think that's what they will do

**Comment by ghost** [comment]
i hope not, at least

**Comment by JamalLyons** [comment]
nah dont do this, Phub exist lmao

**Comment by Assassin-1234** [comment]
watch at it from a business perspective, all that people need a place to go and **YOU** can provide them

**Comment by ghost** [comment]
uh...pornhub exists lol
